// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function API_GetDanmuInfo(arg1) {
  return window['go']['main']['App']['API_GetDanmuInfo'](arg1);
}

export function API_GetLiveUserInfo(arg1) {
  return window['go']['main']['App']['API_GetLiveUserInfo'](arg1);
}

export function API_GetRoomInfo(arg1) {
  return window['go']['main']['App']['API_GetRoomInfo'](arg1);
}

export function API_GetRoomInit(arg1) {
  return window['go']['main']['App']['API_GetRoomInit'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function OnLive() {
  return window['go']['main']['App']['OnLive']();
}

export function SavePic(arg1) {
  return window['go']['main']['App']['SavePic'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
